version: '3.8'

services:
  frontend:
    build:
    context: .
    dockerfile: Dockerfile
    args:
      NEXT_DISABLE_ESLINT: "true" # Disable ESLint during build
    container_name: frontend
    restart: always
    networks:
      - proxy
    environment:
      NEXT_PUBLIC_API_BASE_URL: "https://api.enginchantier.ma"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.frontend.rule=Host(`enginchantier.ma`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
